name: Reproducer builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
